import type { AppState } from "./types";

export const initialState: AppState = {
  version: 2,
  selectedDayId: "today",
  user: {
    name: "Никита",
    goal: "Минус 6 кг и сильнее верх тела",
    phase: "Неделя 3 из 12",
    day: 18,
    readiness: 82,
    streak: 12,
    notifications: true,
    privacy: "Фото прогресса скрыты от всех, кроме тренера",
    coach: {
      name: "Алексей Морозов",
      role: "Тренер",
      note: "Сегодня держим белок и не гоним вес в жиме. Техника важнее цифры.",
      avatar: "АМ",
    },
  },
  nutritionGoal: {
    caloriesGoal: 2200,
    proteinGoal: 126,
    carbsGoal: 230,
    fatGoal: 70,
  },
  days: [
    {
      id: "yesterday",
      dateLabel: "Вчера",
      weekday: "Вторник, 26 мая",
      summary: "Питание закрыто, тренировка пропущена",
      readiness: 71,
      waterMl: 1800,
      waterGoalMl: 2400,
      tasks: [
        {
          id: "y-meal",
          time: "готово",
          title: "План питания закрыт",
          detail: "Белок 118 г, калории в коридоре.",
          action: "Посмотреть",
          type: "meal",
          targetId: "breakfast",
          href: "/nutrition",
          accent: "mint",
          status: "done",
        },
      ],
    },
    {
      id: "today",
      dateLabel: "Сегодня",
      weekday: "Среда, 27 мая",
      summary: "2 приема пищи, тренировка и короткий check-in",
      readiness: 82,
      waterMl: 1400,
      waterGoalMl: 2400,
      tasks: [
        {
          id: "meal-1",
          time: "через 45 мин",
          title: "Обед с высоким белком",
          detail: "Курица, крупа и овощи. Нужно закрыть 42 г белка.",
          action: "Залогировать обед",
          type: "meal",
          targetId: "lunch",
          href: "/nutrition/lunch",
          accent: "coral",
          status: "next",
        },
        {
          id: "workout-1",
          time: "18:00",
          title: "Верх тела: техника + объем",
          detail: "5 упражнений, 48 минут. Тренер снизил рабочий вес на первом упражнении.",
          action: "Начать тренировку",
          type: "workout",
          href: "/training/session",
          accent: "lime",
          status: "planned",
        },
        {
          id: "checkin-1",
          time: "21:30",
          title: "Вечерний check-in",
          detail: "Самочувствие, голод, сон и фото ужина одним экраном.",
          action: "Заполнить",
          type: "checkin",
          href: "/check-in",
          accent: "aqua",
          status: "planned",
        },
        {
          id: "progress-1",
          time: "утро",
          title: "Замер талии",
          detail: "Раз в неделю добавь вес, талию и фото формы.",
          action: "Добавить замер",
          type: "progress",
          href: "/progress/new",
          accent: "violet",
          status: "planned",
        },
      ],
    },
    {
      id: "tomorrow",
      dateLabel: "Завтра",
      weekday: "Четверг, 28 мая",
      summary: "Легкая активность и заготовка еды",
      readiness: 78,
      waterMl: 0,
      waterGoalMl: 2400,
      tasks: [
        {
          id: "t-walk",
          time: "после ужина",
          title: "30 минут ходьбы",
          detail: "Низкая нагрузка после силовой тренировки.",
          action: "Открыть план",
          type: "workout",
          href: "/training",
          accent: "aqua",
          status: "planned",
        },
      ],
    },
  ],
  meals: [
    {
      id: "breakfast",
      title: "Омлет с индейкой",
      tag: "съедено",
      calories: 420,
      protein: 36,
      carbs: 18,
      fat: 22,
      time: "09:10",
      portion: 1,
      accent: "mint",
      state: "eaten",
      ingredients: ["2 яйца", "индейка", "зелень", "томат"],
      note: "Хороший старт дня, можно добавить овощей.",
    },
    {
      id: "lunch",
      title: "Боул с курицей",
      tag: "рекомендация",
      calories: 610,
      protein: 48,
      carbs: 64,
      fat: 18,
      time: "13:30",
      portion: 1,
      accent: "coral",
      state: "suggested",
      ingredients: ["курица", "рис", "овощи", "соус йогурт"],
      note: "Закрывает основной белок до тренировки.",
    },
    {
      id: "dinner",
      title: "Рыба, рис и салат",
      tag: "план",
      calories: 520,
      protein: 42,
      carbs: 52,
      fat: 16,
      time: "20:10",
      portion: 1,
      accent: "aqua",
      state: "planned",
      ingredients: ["белая рыба", "рис", "салат", "оливковое масло"],
      note: "После тренировки оставь углеводы, не режь ужин.",
    },
  ],
  recipes: [
    {
      id: "recipe-1",
      title: "Творожный боул с ягодами",
      tag: "быстро",
      time: "7 мин",
      calories: 360,
      protein: 32,
      accent: "violet",
    },
    {
      id: "recipe-2",
      title: "Куриные ножки в кляре fit",
      tag: "рецепт недели",
      time: "40 мин",
      calories: 540,
      protein: 44,
      accent: "coral",
    },
    {
      id: "recipe-3",
      title: "Паста с тунцом",
      tag: "после тренировки",
      time: "18 мин",
      calories: 610,
      protein: 46,
      accent: "lime",
    },
  ],
  workout: {
    title: "Верх тела: техника + объем",
    duration: "48 мин",
    focus: "Грудь, плечи, трицепс",
    readinessNote: "Готовность высокая, но сон ниже обычного. Оставь 1 повтор в запасе.",
    exercises: [
      {
        id: "bench",
        name: "Жим штанги лежа",
        muscle: "грудь",
        sets: 4,
        reps: "8-10",
        weight: "62.5 кг",
        rest: "90 сек",
        technique: ["Лопатки сведены", "Стопы плотно в пол", "Штанга касается нижней части груди"],
        coachTip: "Не ускоряй негативную фазу. Сегодня цель — одинаковая траектория.",
        history: ["60 кг × 10", "62.5 кг × 9", "62.5 кг × 8"],
      },
      {
        id: "row",
        name: "Тяга гантели в наклоне",
        muscle: "спина",
        sets: 3,
        reps: "10-12",
        weight: "24 кг",
        rest: "75 сек",
        technique: ["Спина нейтральна", "Локоть идет к тазу", "Пауза в верхней точке"],
        coachTip: "Не разворачивай корпус за гантелью.",
        history: ["22 кг × 12", "24 кг × 10"],
      },
      {
        id: "raise",
        name: "Махи в стороны",
        muscle: "плечи",
        sets: 3,
        reps: "14-16",
        weight: "8 кг",
        rest: "60 сек",
        technique: ["Локти мягкие", "Не поднимай плечи", "Движение до уровня глаз"],
        coachTip: "Лучше легче, но без рывка корпусом.",
        history: ["7 кг × 16", "8 кг × 14"],
      },
      {
        id: "triceps",
        name: "Разгибание на блоке",
        muscle: "трицепс",
        sets: 3,
        reps: "12-14",
        weight: "32 кг",
        rest: "60 сек",
        technique: ["Локти у корпуса", "Плечо неподвижно", "Полное разгибание внизу"],
        coachTip: "Финишируй подход без раскачки.",
        history: ["30 кг × 14", "32 кг × 12"],
      },
    ],
  },
  workoutSession: {
    activeExerciseId: "bench",
    completed: false,
    effort: 7,
    setsByExercise: {
      bench: [
        { id: "bench-1", weight: "62.5", reps: "10", done: true },
        { id: "bench-2", weight: "62.5", reps: "9", done: false },
        { id: "bench-3", weight: "62.5", reps: "", done: false },
      ],
      row: [{ id: "row-1", weight: "24", reps: "", done: false }],
      raise: [{ id: "raise-1", weight: "8", reps: "", done: false }],
      triceps: [{ id: "triceps-1", weight: "32", reps: "", done: false }],
    },
  },
  checkIn: {
    completed: false,
    mood: 7,
    hunger: 4,
    sleep: 6,
    stress: 3,
    comment: "",
    photoStub: "ужин без фото",
  },
  progress: {
    week: "Неделя 3",
    adherence: 87,
    weight: "-1.8 кг",
    waist: "-2.5 см",
    protein: 91,
    training: 4,
    insight:
      "Вес движется медленно, но талия уменьшается. Тренер оставил калории без изменений и добавил шаги после ужина.",
  },
  progressEntries: [
    {
      id: "p1",
      date: "13 мая",
      weight: "86.4",
      waist: "92",
      note: "Старт. Фото сделано утром.",
      photoStub: "старт",
    },
    {
      id: "p2",
      date: "20 мая",
      weight: "85.2",
      waist: "90.6",
      note: "Лучше держу белок, меньше вечернего голода.",
      photoStub: "неделя 2",
    },
  ],
  notifications: [
    {
      id: "n1",
      title: "Комментарий тренера",
      body: "Проверь технику жима перед первым подходом.",
      time: "11:40",
      read: false,
    },
  ],
};

export const user = initialState.user;
export const dailyPlan = initialState.days.find((day) => day.id === "today")!;
export const meals = initialState.meals;
export const workout = initialState.workout;
export const progress = initialState.progress;
export const habitScores = [
  { label: "Белок", value: 91, accent: "lime" },
  { label: "Тренировки", value: 80, accent: "mint" },
  { label: "Сон", value: 68, accent: "aqua" },
  { label: "Вода", value: 74, accent: "violet" },
] as const;
